---
- name: Install acl
  become: true
  hosts: all
  tasks: 
    - name: Install acl
      ansible.builtin.package:
        name: acl
        state: present

- name: Setup PostgreSQL Repo
  become: true
  hosts: all
  tasks:
    - name: Add signing key for Postgres repo to apt
      ansible.builtin.apt_key:
        keyserver: keyserver.ubuntu.com
        id: b97b0afcaa1a47f044f244a07fcc7d46accc4cf8
    - name: Add Postgres repo to sources list
      ansible.builtin.apt_repository: 
        repo: deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main
        state: present
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

- name: Install PostgreSQL Server
  become: true
  hosts: all
  roles:
    - role: geerlingguy.postgresql
      vars:
        postgresql_version: 13
        postgresql_packages:
         - postgresql-13
         - postgresql-contrib
         - libpq-dev
        postgresql_data_dir: "/var/lib/postgresql/13/main"
        postgresql_bin_path: "/usr/lib/postgresql/13/bin"
        postgresql_config_path: "/etc/postgresql/13/main"
      postgresql_databases:
        - name: zabbix
      postgresql_users:
        - name: "{{ zabbix_server_dbuser }}"
          password: "{{ zabbix_server_dbpassword }}"

- name: Install Zabbix Server
  become: true
  hosts: all
  vars:
    zabbix_server_name: "{{ server_name }}"
  roles:
    - role: community.zabbix.zabbix_server
      zabbix_server_version: 6.0
      zabbix_server_database: pgsql
      zabbix_server_database_long: postgresql
      zabbix_server_dbport: 5432
      zabbix_server_dbname: zabbix

- name: Install Zabbix Web Frontend
  become: true
  hosts: all
  vars:
    zabbix_server_name: "{{ server_name }}"
  pre_tasks:
    - name: Install php-fpm
      apt:
        name: php-fpm
        state: present
    - name: Install the Apache web server
      apt:
        name: apache2
        state: present
    - name: Enable the Apache2 module mod_rewrite
      community.general.apache2_module:
        name: rewrite
        state: present
    - name: Disable the default Apache2 site
      ansible.builtin.shell: a2dissite 000-default
  roles:
    - role: community.zabbix.zabbix_web
      zabbix_web_version: 6.0
      zabbix_api_server_url: "{{ zabbix_server_name }}"
      zabbix_server_database: pgsql
      zabbix_server_database_long: postgresql
      zabbix_server_dbport: 5432
      zabbix_server_dbname: zabbix